name: CI
on: [push]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
      - name: Run YAPF
        uses: AlexanderMelde/yapf-action@v1.0
        with:
          args: --verbose --exclude '**/tests/**' --exclude  '**/venv/**' --exclude  '**/build/**' --exclude  '**/.eggs/**'
  tests:
    name: pytest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
      - name: Run pytest
        uses: fylein/python-pytest-github-action@v2
        with:
          args: pip3 install -r requirements.txt && pytest tests -vvv



