name: Publish python distribution to PyPI
on: push

jobs:
  build-and-publish-test:
    name: Build and publish python distribution to PyPI
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7
      - name: Create distribution
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
        continue-on-error: true
      - name: Sleep to allow pypi index to update with the new version
        run: sleep 5m
      - name: Cleanup
        run: |
          rm -r mock_autogen
          pip uninstall mock-generator
      - name: Perform System tests
        run: |
          python -m pip install pip==21.0.1
          pip install -r test-requirements.txt
          pip install -i https://test.pypi.org/simple/ mock-generator
          python -m pytest -vvv -k "test_pytest_mocker or test_public_api or test_safe_travels_on_func_failure"

  build-and-publish-production:
    name: Build and publish python distribution to PyPI
    runs-on: ubuntu-18.04
    if: startsWith(github.event.ref, 'refs/tags')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0
      - name: Set up Python 3.7
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.7
      - name: Create distribution
        run: python setup.py sdist bdist_wheel
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          password: ${{ secrets.pypi_password }}
      - name: Sleep to allow pypi index to update with the new version
        run: sleep 5m
      - name: Cleanup
        run: |
          rm -r mock_autogen
          pip uninstall mock-generator
      - name: Perform System tests
        run: |
          python -m pip install pip==21.0.1
          pip install -r test-requirements.txt
          pip install mock-generator
          python -m pytest -vvv -k "test_pytest_mocker or test_public_api or test_safe_travels_on_func_failure"
